
# Copy this into ~/.dbt/profiles.yml for local runs, or mount into /opt/airflow/dbt in Airflow.
product_catalog:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SF_ACCOUNT') }}"
      user: "{{ env_var('SF_USER') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      role: "{{ env_var('SF_ROLE', 'SYSADMIN') }}"
      database: "PRODUCT_CATALOG"
      warehouse: "{{ env_var('SF_WAREHOUSE', 'COMPUTE_WH') }}"
      schema: "CORE"
      threads: 4
      client_session_keep_alive: False
